db:
  image: mongo
  ports:
    - "27018:27017"
  volumes:
    - ./data:/data/db
web:
  build: .
  command: node server.js
  volumes:
    - .:/usr/src/app
  ports:
    - "4200:8080"
  links:
    - db
  environment:
    PORT: 8080 # this is optional, allows express to use process.env.PORT instead
